[package]
name = "kony-web"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = "0.21"
web-sys = "0.3"
yew-router = "0.18"
yew_icons = {version = "0.8", features = ["BootstrapDiscord", "BootstrapGithub", "FeatherChevronDown"]}
wasm-bindgen = "0.2.87"